services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - PORT=4000
    command: >
      sh -c "npm run db:migrate && 
             npx nodemon -w /app/migrations -e sql -x 'npm run db:migrate' & 
             npm run dev:container"
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  pgdata:
